### ISSUE TITLE
The functionality documentation is not clear

### ISSUE THREAD

**Issue by vals** [bebatut/enasearch#28]
While every command _is_ written out in the documentation, the functionality of the command, what the output is or does, or what the options are, are not described.

Example:
![screen shot 2017-10-02 at 11 59 19](https://user-images.githubusercontent.com/668803/31074584-3bc07e0e-a769-11e7-8712-5645907a8256.png)

Here it would be helpful to describe what an 'analysis field' is, and what the `[OPTIONS]` are. What can I use a list of analysis fields for?

**Comment by bebatut** [comment]
Thanks @vals for this feedback.

I am adding a page in the documentation about the interaction with ENA using ENASearch #35. I hope it will clarified the different type of data.

For the command you shown, there is no `[OPTIONS]` per se (except help) for this command specifically. When there is options for a command, it is described: 

![screen shot 2017-10-03 at 20 29 37](https://user-images.githubusercontent.com/1842467/31142151-b675f032-a879-11e7-9f60-1ad5b118fd7e.png)

I am using a tool that automatically parse the Python file and extract the documentation (description and parameters) from the description of Click to avoid redundancy between command-line description and its documentation online. I do not know how I could remove the `[OPTIONS]` for the commands without parameters...

I will add more details about the outputs of the commands

**Comment by bebatut** [comment]
It should be solved with #36
